### ISSUE TITLE
PHP 8.0 not supported by dependent league libraries

### ISSUE THREAD

**Issue by kartik-v** [yiisoft/yii-file-system#13]
### What steps will reproduce the problem?
- PHP 8.0 environment
- Error in composer install when you wish to install yiisoft/yii-filesystem or yiisoft/yii-debug or yiisoft/app

### What is the expected result?
- Successful composer install for PHP 8.0

### What do you get instead?
- Error in composer install
```
    - league/mime-type-detection[1.0.0, ..., 1.3.0] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
    - league/flysystem[2.0.0-alpha.1, ..., 2.0.0-RC1] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
    - league/mime-type-detection[1.4.0, ..., 1.7.0] require ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
    - yiisoft/yii-debug dev-master requires yiisoft/yii-filesystem dev-master -> satisfiable by yiisoft/yii-filesystem[dev-master].
    - yiisoft/yii-filesystem dev-master requires league/flysystem ^2.0 -> satisfiable by league/flysystem[2.0.0-alpha.1, ..., 2.x-dev].
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.0
| Operating system | Win/Linux

**Comment by vjik** [comment]
Try remove vendor and run `composer update`.

I'm install now success:

![image](https://user-images.githubusercontent.com/525501/117408839-28e3e800-af19-11eb-929c-b30f4052aa49.png)
![image](https://user-images.githubusercontent.com/525501/117408866-326d5000-af19-11eb-8840-c863a5c43d23.png)

**Comment by kartik-v** [comment]
Sorry - not sure - does not seem to work.

**Comment by samdark** [comment]
Cannot reproduce it. Installs well on PHP 8:

![image](https://user-images.githubusercontent.com/47294/117421640-6485ae80-af27-11eb-9a76-4457df29252c.png)

**Comment by kartik-v** [comment]
Will check if anything else different and update.

**Comment by kartik-v** [comment]
After manually cloning the yii-filesystem repo if I change the dependency from `"league/flysystem": "^2.0", `  to `"league/flysystem": "@dev", ` then it works when I update via composer. Seems it could be a composer issue itself in the environment. Will check. With the dependency `"league/flysystem": "^2.0", ` -- the following error is thrown:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/flysystem[2.0.0, ..., 2.x-dev] require league/mime-type-detection ^1.0.0 -> satisfiable by league/mime-type-detection[1.0.0, ..., 1.7.0].
    - league/flysystem[2.0.0-alpha.1, ..., 2.0.0-RC1] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
    - league/mime-type-detection[1.0.0, ..., 1.3.0] require php ^7.2 -> your php version (8.0.3) does not satisfy that requirement.
    - league/mime-type-detection[1.4.0, ..., 1.7.0] require ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
    - Root composer.json requires league/flysystem ^2.0 -> satisfiable by league/flysystem[2.0.0-alpha.1, ..., 2.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\UniserverZ\core\php80\php-cli.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by kartik-v** [comment]
Ok I achieved this via the following composer option (for folks who are facing this issue and interested)

```
composer require yiisoft/yii-filesystem --ignore-platform-reqs
```

**Comment by samdark** [comment]
I've removed ingoring platform requirements for PHP 8 and it passes. Means it's installed well: https://github.com/yiisoft/yii-filesystem/runs/2526067455. Likely you have outdated Composer cache somewhere because in stable version PHP 8 is allowed: https://github.com/thephpleague/flysystem/blob/2.0.5/composer.json#L20

**Comment by kartik-v** [comment]
Will check since I recently upgraded to PHP 8.. there could be some caching issues with composer.

**Comment by kartik-v** [comment]
Yes indeed - it was a composer cache issue. For the benefit of folks who are upgrading their PHP version from 7.x to 8.x - the following steps may help overcome this issue:

1. Clean your composer cache files (depending on the OS - location of composer cache files may change)
2. Delete the composer.lock file of your app
3. Delete the vendor folder of your app
4. Run `composer install --prefer-dist`  --- everything works fine again.

**Comment by kartik-v** [comment]
Ah ha... detected the issue after close debugging.

The `php-cli.ini` (console PHP config) - must have the `extension=fileinfo` enabled. If we try running composer install without this enabled it, results in composer throwing up the errors mentioned above. The `fileinfo` php library extension is needed for the `league/flysystem` library and subsequently results in error in installing the `yii-filesystem` which depends on it as well. Maybe good to document this. 😄
