### ISSUE TITLE
Introduce FileSystemInterface, make helper create instance and call its methods

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-file-system#2]
- [x] Research existing implementations
- [x] Introduce FileSystemInterface
- [x] Create PHP implementation
- [x] Create dummy implementation, write tests
- [ ] Make helper create instance and call its methods

**Comment by mapeveri** [comment]
@samdark what is the idea with this helper?. Maybe a static method in the same or a new class with a static method for instance Filesystem?

**Comment by mapeveri** [comment]
@samdark what is the idea with this helper?. Maybe a new class with a static method for instance Filesystem or a factory?

**Comment by samdark** [comment]
You mean with the package? It was meant to abstract out the implementation so we can switch from FlySystem to something else if needed. Currently the abstraction leaks too much and that should be fixed.

**Comment by samdark** [comment]
Not sure about what did I mean with that helper :)

**Comment by samdark** [comment]
I think this one could be considered as done.
